export enum AiReply {
    VIEW_ID = "ai-reply-view-id",
    TITLE = "Ai Reply",
    CLOSE_BUTTON_TEXT = "Close",
    CLOSE_ACTION = "ai-reply-close-action-id",
    CLOSE_BLOCK = "ai-reply-close-block-id",
    GENERATE_BUTTON_TEXT = "Generate reply",
    GENERATE_BUTTON_ACTION = "ai-reply-generate-action-id",
    GENERATE_BUTTON_BLOCK = "ai-reply-generate-block-id",
    SEND_BUTTON_TEXT = "Send Message",
    SEND_BUTTON_ACTION = "ai-reply-send-action-id",
    SEND_BUTTON_BLOCK = "ai-reply-send-block-id",
    PROMPT_INPUT_LABEL = "Message",
    PROMPT_INPUT_ACTION = "ai-reply-prompt-input-action-id",
    PROMPT_INPUT_BLOCK = "ai-reply-prompt-input-block-id",
    REPLY_MESSAGE_LABEL = "Reply",
    REPLY_MESSAGE_INPUT_ACTION = "ai-reply-reply-message-action-id",
    REPLY_MESSAGE_INPUT_BLOCK = "ai-reply-reply-message-block-id",
}
