export enum SaveMessage {
    VIEW_ID = "save-message-view-id",
    TITLE = "Save New Message",
    CLOSE_BUTTON_TEXT = "Close",
    CLOSE_ACTION = "save-message-close-action-id",
    CLOSE_BLOCK = "save-message-close-block-id",
    SAVE_MESSAGE_SUBMIT_ACTION = "save-message-submit-action-id",
    SAVE_MESSAGE_SUBMIT_BLOCK = "save-message-submit-block-id",
    ID_INPUT_PLACEHOLDER = "You can directly access message using this id",
    ID_INPUT_LABEL = "Enter id",
    ID_INPUT_ACTION = "input-action-id",
    ID_INPUT_BLOCK = "input-block-id",
    MESSAGE_INPUT_PLACEHOLDER = "Enter your message",
    MESSAGE_INPUT_LABEL = "Enter message",
    MESSAGE_INPUT_ACTION = "message-input-action-id",
    MESSAGE_INPUT_BLOCK = "message-input-block-id",
    SAVE_BUTTON_TEXT = "Save Message",
    SAVE_BUTTON_ACTION = "save-button-action-id",
    SAVE_BUTTON_BLOCK = "save-button-block-id",
}
