export enum SaveMessage {
    VIEW_ID = "save-message-view-id",
    TITLE = "Save New Message",
    CLOSE_BUTTON_TEXT = "Close",
    CLOSE_ACTION = "save-message-close-action-id",
    CLOSE_BLOCK = "save-message-close-block-id",
    SAVE_MESSAGE_SUBMIT_ACTION = "save-message-submit-action-id",
    SAVE_MESSAGE_SUBMIT_BLOCK = "save-message-submit-block-id",
    ID_INPUT_PLACEHOLDER = "You can directly access message using this id",
    ID_INPUT_LABEL = "Enter id",
    ID_INPUT_ACTION = "save-message-id-input-action-id",
    ID_INPUT_BLOCK = "save-message-id-input-block-id",
    MESSAGE_INPUT_PLACEHOLDER = "Enter your message",
    MESSAGE_INPUT_LABEL = "Enter message",
    MESSAGE_INPUT_ACTION = "save-message-message-input-action-id",
    MESSAGE_INPUT_BLOCK = "save-message-message-input-block-id",
    SAVE_BUTTON_TEXT = "Save Message",
    SAVE_BUTTON_ACTION = "save-message-save-button-action-id",
    SAVE_BUTTON_BLOCK = "save-message-save-button-block-id",
    DELETE_BUTTON_TEXT = "Delete",
    DELETE_BUTTON_ACTION = "save-message-delete-button-action-id",
    DELETE_BUTTON_BLOCK = "save-message-delete-button-block-id",
}
